InsuranceCompany/Models/Insurance.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace InsuranceCompany.Models
{
    public class Insurance
    {
        public enum InsuranceType
        {
            [Display(Name = "Životní pojištění")]
            LifeInsurance,

            [Display(Name = "Trvalé poškození")]
            PermanentDamage
        }

        public int Id { get; set; }

        [Display(Name = "Druh pojištění")]
        public InsuranceType Type { get; set; }

        [Display(Name = "Pojištěnec")]
        public Client InsuredPerson { get; set; }
        public int InsuredPersonId { get; set; }

        [Display(Name = "Pojistitel")]
        public Client Insurer { get; set; }
        public int InsurerId { get; set; }

        [Display(Name = "Pojistná částka")]
        [Required(ErrorMessage = "Zadejte, prosíme, pojistnou částku!")]
        [Range(1000, 1000000, ErrorMessage = "Pojistná částka musí být v rozmezí 1 000 - 1 000 000!")]
        public decimal InsuredAmount { get; set; }

        [Display(Name = "Měsíční splátka")]
        [Required(ErrorMessage = "Zadejte, prosíme, měsíční splátku!")]
        [Range(1000, 50000, ErrorMessage = "Splátka musí být v rozmezí 1 000 - 50 000!")]
        public decimal Instalment { get; set; }

        [Display(Name = "Počátek pojištění")]
        [Required(ErrorMessage = "Zadejte, prosíme, počáteční datum pojištění.")]
        [DataType(DataType.Date)]
        public DateOnly InsuranceStartDate { get; set; }

        [Display(Name = "Konec pojištění")]
        [Required(ErrorMessage = "Zadejte, prosíme, konečné datum pojištění.")]
        [DataType(DataType.Date)]
        public DateOnly InsuranceEndDate { get; set; }

        /// <summary>
        /// Kontrola velikosti splátky oproti celkové splatné sumě
        /// </summary>
        /// <returns></returns>
        public bool IsInstalmentSmaller() => InsuredAmount > Instalment;
    }
}

InsuranceCompany/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceCompany.Data;
using InsuranceCompany.Models;
using InsuranceCompany.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceCompany.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Metoda Index. Základní pohled na přehled klientů.
        /// </summary>
        /// <returns>Pohled se seznamem klientů</returns>
        public async Task<IActionResult> Index()
        {
            return View(await _context.Client.ToListAsync());
        }
        /// <summary>
        /// Metoda Details. Zobrazení detailů klienta na základě předaného ID.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>Pohled s detaily klienta v případě, že je nalezen</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var personView = new PersonDetailsViewModel();
            personView.Client = await _context.Client
                .SingleOrDefaultAsync(m => m.Id == id);
            personView.InsuranceContracts = await _context.Insurance
                .Include(i => i.InsuredPerson)
                .ToListAsync();
            personView.InsurerContracts = await _context.Insurance
                .Include(i => i.Insurer)
                .ToListAsync();
            personView.InstalmentsSum = personView.InsurerContracts
                .Sum(x => x.Instalment);
            return View(personView);
        }
        /// <summary>
        /// Metoda Create GET. Zobrazení prázdného formuláře k založení nového klienta.
        /// </summary>
        /// <returns>Základní pohled na formulář k vytvoření klienta bez modelu</returns>
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Metoda Create POST. Odeslání formuláře s vyplněnými údaji o osobě. Provedení kontrol vstupů.
        /// </summary>
        /// <param name="person"> Osoba přijatá z formuláře</param>
        /// <returns>V případě úspěchu návrat na seznam klientů, v případě neúspěchu pohled s modelem klienta.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthNumber,Age,Street,HouseNumber,City,PostCode,Country,Phone")] Client person)
        {
            person.RepairBirthNumber();
            if (!person.PhoneNumberCheckAndFormat())
            {
                ViewBag.PhoneNumberError = "Zadejte platné telefonní číslo ve formátu 123 456 789 nebo 123456789";
                return View(person);
            }
            if (!person.PostCodeCheckAndFormat())
            {
                ViewBag.PostCodeError = "Zadejte platné PSČ ve formátu 123 56 nebo 12345!";
                return View(person);
            }
            if (ModelState.IsValid && person.CheckBirthNumber())
            {
                person.TrimTextInputs();
                person.GetGender();
                person.GetAge();
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else ViewBag.BirthNumberError = "Neplatné rodné číslo!";
            return View(person);
        }
        /// <summary>
        /// Metoda Edit GET. Zobrazení detailů klienta na základě předaného ID.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <param name="person">V případě úspěchu pohled s formulářem naplněným údaji o klientovi</param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Client.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }
        /// <summary>
        /// Metoda Edit POST. Odeslání formuláře s úpravami klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <param name="person">Upravovaný klient</param>
        /// <returns>V případě úspěchu návrat na seznam klienta, v případě neúspěchu pohled s vyplněným formulářem</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthNumber,Sex,Age,Street,HouseNumber,City,PostCode,Country,Phone")] Client person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }
            person.RepairBirthNumber();
            if (!person.PhoneNumberCheckAndFormat())
            {
                ViewBag.PhoneNumberError = "Zadejte platné telefonní číslo ve formátu 123 456 789 nebo 123456789";
                return View(person);
            }
            if (!person.PostCodeCheckAndFormat())
            {
                ViewBag.PostCodeError = "Zadejte platné PSČ ve formátu 123 56 nebo 123456!";
                return View(person);
            }
            if (ModelState.IsValid && person.CheckBirthNumber())
            {
                try
                {
                    person.TrimTextInputs();
                    person.GetGender();
                    person.GetAge();
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else ViewBag.BirthNumberError = "Neplatné rodné číslo!";
            return View(person);
        }
        /// <summary>
        /// Metoda Delete GET. Zobrazení formuláře s údaji o klientovi k vymazání.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>V případě úspěchu pohled s modelem mazaného klienta.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }
        /// <summary>
        /// Metoda Delete POST. Odeslání formuláře s potvrzením vymazání klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>V případě úspěchu a vymazání klienta návrat na přehled klienta. V případě neúspěchu pohled s modelem klienta.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Client
                .FindAsync(id);
            var contracts = await _context.Insurance
                .FirstAsync(m => m.InsuredPersonId == id);
            if (person != null && contracts == null)
            {
                _context.Client.Remove(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Error = "Uživatel má stále aktivní pojistku! Před vymazáním nutné odstranit.";
            return View(person);
        }
        /// <summary>
        /// Kontrola existence klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>True pokud je klient nalezen</returns>
        private bool PersonExists(int id)
        {
            return _context.Client.Any(e => e.Id == id);
        }
    }
}

InsuranceCompany/Controllers/InsuredEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceCompany.Data;
using InsuranceCompany.Models;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using NuGet.Protocol.Core.Types;
using Humanizer;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceCompany.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class InsuredEventsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InsuredEventsController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Metoda Index. Pohled na výpis událostí. 
        /// </summary>
        /// <returns>Pohled s listem pojistných událostí</returns>
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.InsuredEvent
                .Include(i => i.Insurance)
                .Include(i => i.Client);
            return View(await applicationDbContext.ToListAsync());
        }
        /// <summary>
        /// Metoda Create GET. Zobrazuje formulář k založení události s předvyplněnými údaji o pojistce, ke které se váže.
        /// </summary>
        /// <param name="id">Číselný identifikátor události</param>
        /// <returns>Pohled na formulář k založení události bez modelu</returns>
        public async Task<IActionResult> Create(int? id)
        {
            var insurance = await _context.Insurance
                .FirstOrDefaultAsync(m => m.Id == id);
            var person = await _context.Client
                .Where(x => x.Id == insurance.InsuredPersonId)
                .FirstOrDefaultAsync();
            ViewBag.Insurance = insurance;
            ViewBag.Client = person;
            return View();
        }
        /// <summary>
        /// Metoda Create POST. Odeslání formuláře k založení pojistné události.
        /// </summary>
        /// <param name="insuredEvent">Model pojistné události</param>
        /// <returns>V případě úspěchu přesměrování na výpis událostí.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InsuranceId,ClientId,Description,State")] InsuredEvent insuredEvent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(insuredEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(insuredEvent);
        }
        /// <summary>
        /// Metoda Edit GET. Zobrazení formuláře k editaci pojistné události.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistné události</param>
        /// <returns>Pohled s modelem události</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var insuredEvent = await _context.InsuredEvent.FindAsync(id);
            if (insuredEvent == null)
            {
                return NotFound();
            }
            return View(insuredEvent);
        }
        /// <summary>
        /// Metoda Edit POST. Odeslání formuláře k editaci pojistné události
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistné události</param>
        /// <param name="insuredEvent">Model pojistné události</param>
        /// <returns>V případě úspěchu přesměrování na výpis událost, v případě neúspěchu pohled s modelem upravované události</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,InsuranceId,ClientId,Description,State")] InsuredEvent insuredEvent)
        {
            if (id != insuredEvent.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(insuredEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InsuredEventExists(insuredEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(insuredEvent);
        }
        /// <summary>
        /// Metoda Delete GET. Zobrazení detailu události před smazáním
        /// </summary>
        /// <param name="id">Číselný identifikátor události</param>
        /// <returns>Pohled s modelem události</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var insuredEvent = await _context.InsuredEvent
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insuredEvent == null)
            {
                return NotFound();
            }
            return View(insuredEvent);
        }
        /// <summary>
        /// Metoda DeleteConfirmed POST. Odeslání potvrzení vymazání události.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistné události.</param>
        /// <returns>V případě úspěchu přesměrování na seznam událostí.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var insuredEvent = await _context.InsuredEvent.FindAsync(id);
            if (insuredEvent != null)
            {
                _context.InsuredEvent.Remove(insuredEvent);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        /// <summary>
        /// Kontrola existence konkrétní události.
        /// </summary>
        /// <param name="id">Číselný identifikátor události</param>
        /// <returns>True v případě existence události.</returns>
        private bool InsuredEventExists(int id)
        {
            return _context.InsuredEvent.Any(e => e.Id == id);
        }
    }
}

InsuranceCompany/Views/Insurances/Create.cshtml
@model InsuranceCompany.Models.Insurance

@{
    ViewData["Title"] = "Tvorba pojištění";
}

<section class="bg-dark py-5">
    <div class="container px-5 my-5 px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form class="d-flex flex-column gap-4" id="contactForm" asp-action="Create">
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="Type" asp-items="@Html.GetEnumSelectList<Insurance.InsuranceType>()"></select>
                        <label asp-for="Type"></label>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="InsuredPersonId" asp-items="ViewBag.InsuredPersonId"></select>
                        <label asp-for="InsuredPersonId">Rodné číslo pojištěnce</label>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="InsurerId" asp-items="ViewBag.InsurerId"></select>
                        <label asp-for="InsurerId">Rodné číslo pojistitele</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuredAmount" type="number" placeholder="100000" />
                        <label asp-for="InsuredAmount"></label>
                        <span asp-validation-for="InsuredAmount" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Instalment" type="number" placeholder="1000" />
                        <label asp-for="Instalment"></label>
                        <span asp-validation-for="Instalment" class="text-danger"></span>
                        @if (ViewBag.Error != null)
                        {
                            <p class="text-danger m-0">@ViewBag.Error</p>
                        }
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceStartDate" />
                        <label asp-for="InsuranceStartDate"></label>
                        <span asp-validation-for="InsuranceStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceEndDate" />
                        <label asp-for="InsuranceEndDate"></label>
                        <span asp-validation-for="InsuranceEndDate" class="text-danger"></span>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary btn-lg" type="submit">Odeslat</button>
                    </div>
                    <div class="d-grid">
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InsuranceCompany/Views/Insurances/Delete.cshtml
@model InsuranceCompany.Models.Insurance

@{
    ViewData["Title"] = "Vymazání pojištění";
}

<section class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center my-5">
                    <h1 class="display-5 fw-bolder text-white mb-2">Vymazání pojistky</h1>
                    <p class="lead text-white-50 mb-4">Opravdu si přejete ji smazat?</p>
                    <div class="text-white">
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Type)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Type)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.InsuredPerson)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.InsuredPerson.Id) |
                                @Html.DisplayFor(model => model.InsuredPerson.FirstName) @Html.DisplayFor(model => model.InsuredPerson.LastName) |
                                <a asp-controller="People" asp-action="Details" asp-route-id="@Model?.InsuredPersonId">Detail pojištěnce</a>
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Insurer)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Insurer.Id) |
                                @Html.DisplayFor(model => model.Insurer.FirstName) @Html.DisplayFor(model => model.Insurer.LastName) |
                                <a asp-controller="People" asp-action="Details" asp-route-id="@Model?.InsurerId">Detail pojistitele</a>
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.InsuredAmount)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.InsuredAmount)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Instalment)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Instalment)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.InsuranceStartDate)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.InsuranceStartDate)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.InsuranceEndDate)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.InsuranceEndDate)
                            </dd>
                        </dl>
                    </div>
                    <hr />
                    <form class="d-grid" asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Smaž" class="btn btn-danger btn-lg" />
                        <hr />
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </form>
                    @if (ViewBag.Error != null)
                    {
                        <p class="text-danger m-0">@ViewBag.Error</p>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

InsuranceCompany/Views/Insurances/Edit.cshtml
@model InsuranceCompany.Models.Insurance

@{
    ViewData["Title"] = "Úprava pojištění";
}

<section class="bg-dark py-5">
    <div class="container px-5 my-5 px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form class="d-flex flex-column gap-4" id="contactForm" asp-action="Edit">
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="Type" asp-items="@Html.GetEnumSelectList<Insurance.InsuranceType>()"></select>
                        <label asp-for="Type"></label>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="InsuredPersonId" class="form-control" asp-items="ViewBag.InsuredPersonId"></select>
                        <label asp-for="InsuredPersonId">Rodné číslo pojištěnce</label>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="InsurerId" asp-items="ViewBag.InsurerId"></select>
                        <label asp-for="InsurerId">Rodné číslo pojistitele</label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuredAmount" type="number" placeholder="100000" />
                        <label asp-for="InsuredAmount"></label>
                        <span asp-validation-for="InsuredAmount" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Instalment" type="number" placeholder="1000" />
                        <label asp-for="Instalment"></label>
                        <span asp-validation-for="Instalment" class="text-danger"></span>
                        @if (ViewBag.Error != null)
                        {
                            <p class="text-danger m-0">@ViewBag.Error</p>
                        }
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceStartDate" />
                        <label asp-for="InsuranceStartDate"></label>
                        <span asp-validation-for="InsuranceStartDate" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceEndDate" />
                        <label asp-for="InsuranceEndDate"></label>
                        <span asp-validation-for="InsuranceEndDate" class="text-danger"></span>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary btn-lg" type="submit">Odeslat</button>
                    </div>
                    <div class="d-grid">
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

InsuranceCompany/Views/Insurances/Index.cshtml
@model IEnumerable<InsuranceCompany.Models.Insurance>

@{
    ViewData["Title"] = "Správa pojištění";
}

<section class="bg-dark py-5 border-bottom text-white">
    <div class="container px-5 my-5">
        <div class="text-center mb-5">
            <h2 class="fw-bolder">Správa pojištění</h2>
        </div>
        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
            <a class="btn btn-outline-light btn-lg px-4" asp-action="Create">Vytvoř nové pojištění</a>
            <a class="btn btn-outline-light btn-lg px-4" asp-controller="InsuredEvents" asp-action="Index">Pojistné události</a>
            <a class="btn btn-outline-light btn-lg px-4" asp-controller="Clients" asp-action="Index">Správa osob</a>
        </div>
    </div>
    <div class="container">
        <table class="table table-responsive table-hover table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.InsuredPerson)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Insurer)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.InsuredAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Instalment)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.InsuranceStartDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.InsuranceEndDate)
                    </th>
                    <th class="text-center">
                        Akce
                    </th>
                </tr>
            </thead>
            <tbody class="table-light">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuredPerson.FirstName) @Html.DisplayFor(modelItem => item.InsuredPerson.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Insurer.FirstName) @Html.DisplayFor(modelItem => item.Insurer.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuredAmount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Instalment)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceStartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.InsuranceEndDate)
                        </td>
                        <td class="text-center">
                            <a asp-action="Edit" asp-route-id="@item.Id">Uprav</a> |
                            <a asp-controller="InsuredEvents" asp-action="Create" asp-route-id="@item.Id">Události</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">Detaily</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Smaž</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>