InsuranceCompany/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceCompany.Data;
using InsuranceCompany.Models;
using InsuranceCompany.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceCompany.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ClientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ClientsController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Metoda Index. Základní pohled na přehled klientů.
        /// </summary>
        /// <returns>Pohled se seznamem klientů</returns>
        public async Task<IActionResult> Index()
        {
            return View(await _context.Client.ToListAsync());
        }
        /// <summary>
        /// Metoda Details. Zobrazení detailů klienta na základě předaného ID.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>Pohled s detaily klienta v případě, že je nalezen</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var personView = new PersonDetailsViewModel();
            personView.Client = await _context.Client
                .SingleOrDefaultAsync(m => m.Id == id);
            personView.InsuranceContracts = await _context.Insurance
                .Include(i => i.InsuredPerson)
                .ToListAsync();
            personView.InsurerContracts = await _context.Insurance
                .Include(i => i.Insurer)
                .ToListAsync();
            personView.InstalmentsSum = personView.InsurerContracts
                .Sum(x => x.Instalment);
            return View(personView);
        }
        /// <summary>
        /// Metoda Create GET. Zobrazení prázdného formuláře k založení nového klienta.
        /// </summary>
        /// <returns>Základní pohled na formulář k vytvoření klienta bez modelu</returns>
        public IActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// Metoda Create POST. Odeslání formuláře s vyplněnými údaji o osobě. Provedení kontrol vstupů.
        /// </summary>
        /// <param name="person"> Osoba přijatá z formuláře</param>
        /// <returns>V případě úspěchu návrat na seznam klientů, v případě neúspěchu pohled s modelem klienta.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,BirthNumber,Age,Street,HouseNumber,City,PostCode,Country,Phone")] Client person)
        {
            person.RepairBirthNumber();
            if (!person.PhoneNumberCheckAndFormat())
            {
                ViewBag.PhoneNumberError = "Zadejte platné telefonní číslo ve formátu 123 456 789 nebo 123456789";
                return View(person);
            }
            if (!person.PostCodeCheckAndFormat())
            {
                ViewBag.PostCodeError = "Zadejte platné PSČ ve formátu 123 56 nebo 12345!";
                return View(person);
            }
            if (ModelState.IsValid && person.CheckBirthNumber())
            {
                person.TrimTextInputs();
                person.GetGender();
                person.GetAge();
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else ViewBag.BirthNumberError = "Neplatné rodné číslo!";
            return View(person);
        }
        /// <summary>
        /// Metoda Edit GET. Zobrazení detailů klienta na základě předaného ID.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <param name="person">V případě úspěchu pohled s formulářem naplněným údaji o klientovi</param>
        /// <returns></returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Client.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }
        /// <summary>
        /// Metoda Edit POST. Odeslání formuláře s úpravami klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <param name="person">Upravovaný klient</param>
        /// <returns>V případě úspěchu návrat na seznam klienta, v případě neúspěchu pohled s vyplněným formulářem</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,BirthNumber,Sex,Age,Street,HouseNumber,City,PostCode,Country,Phone")] Client person)
        {
            if (id != person.Id)
            {
                return NotFound();
            }
            person.RepairBirthNumber();
            if (!person.PhoneNumberCheckAndFormat())
            {
                ViewBag.PhoneNumberError = "Zadejte platné telefonní číslo ve formátu 123 456 789 nebo 123456789";
                return View(person);
            }
            if (!person.PostCodeCheckAndFormat())
            {
                ViewBag.PostCodeError = "Zadejte platné PSČ ve formátu 123 56 nebo 123456!";
                return View(person);
            }
            if (ModelState.IsValid && person.CheckBirthNumber())
            {
                try
                {
                    person.TrimTextInputs();
                    person.GetGender();
                    person.GetAge();
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else ViewBag.BirthNumberError = "Neplatné rodné číslo!";
            return View(person);
        }
        /// <summary>
        /// Metoda Delete GET. Zobrazení formuláře s údaji o klientovi k vymazání.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>V případě úspěchu pohled s modelem mazaného klienta.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }
        /// <summary>
        /// Metoda Delete POST. Odeslání formuláře s potvrzením vymazání klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>V případě úspěchu a vymazání klienta návrat na přehled klienta. V případě neúspěchu pohled s modelem klienta.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Client
                .FindAsync(id);
            var contracts = await _context.Insurance
                .FirstAsync(m => m.InsuredPersonId == id);
            if (person != null && contracts == null)
            {
                _context.Client.Remove(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Error = "Uživatel má stále aktivní pojistku! Před vymazáním nutné odstranit.";
            return View(person);
        }
        /// <summary>
        /// Kontrola existence klienta.
        /// </summary>
        /// <param name="id">Číselný identifikátor klienta</param>
        /// <returns>True pokud je klient nalezen</returns>
        private bool PersonExists(int id)
        {
            return _context.Client.Any(e => e.Id == id);
        }
    }
}

InsuranceCompany/Controllers/InsurancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsuranceCompany.Data;
using InsuranceCompany.Models;
using Microsoft.AspNetCore.Authorization;

namespace InsuranceCompany.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class InsurancesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InsurancesController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Metoda Index. Základní pohled na přehled pojištění.
        /// </summary>
        /// <returns>Pohled se seznamem pojištění.</returns>
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Insurance.Include(i => i.InsuredPerson).Include(i => i.Insurer);
            return View(await applicationDbContext.ToListAsync());
        }
        /// <summary>
        /// Metoda Details. Zobrazení detailů pojištění na základě předaného ID.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <returns>Pohled s detaily pojistky v případě, že je nalezena.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var insurance = await _context.Insurance
                .Include(i => i.InsuredPerson)
                .Include(i => i.Insurer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insurance == null)
            {
                return NotFound();
            }
            return View(insurance);
        }
        /// <summary>
        /// Metoda Create GET. Zobrazení prázdného formuláře k založení nové pojistky a dohledání možných klientů do výběrových seznamů ve formuláři.
        /// </summary>
        /// <returns>Základní pohled na formulář k vytvoření pojistky bez modelu</returns>
        public IActionResult Create()
        {
            ViewData["InsuredPersonId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber");
            ViewData["InsurerId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber");
            return View();
        }
        /// <summary>
        /// Metoda Create POST. Odeslání formuláře s vyplněnými údaji o pojistce.
        /// </summary>
        /// <param name="insurance">Pojistka přijatá z formuláře</param>
        /// <returns>V případě úspěchu návrat na seznam pojistek, v případě neúspěchu pohled s modelem pojistky.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Type,InsuredPersonId,InsurerId,InsuredAmount,Instalment,InsuranceStartDate,InsuranceEndDate")] Insurance insurance)
        {
            if (ModelState.IsValid && insurance.IsInstalmentSmaller())
            {
                _context.Add(insurance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Error = "Splátka nesmí být větší než celková suma.";
            ViewData["InsuredPersonId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber", insurance.InsuredPersonId);
            ViewData["InsurerId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber");
            return View(insurance);
        }
        /// <summary>
        /// Metoda Edit GET. Zobrazení detailů pojistky na základě předaného ID. 
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <returns>V případě úspěchu pohled s formulářem naplněným údaji o pojistce</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var insurance = await _context.Insurance.FindAsync(id);
            if (insurance == null)
            {
                return NotFound();
            }
            ViewData["InsuredPersonId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber", insurance.InsuredPersonId);
            ViewData["InsurerId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber");
            return View(insurance);
        }
        /// <summary>
        /// Metoda Edit POST. Odeslání formuláře s úpravami pojistky.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <param name="insurance">Upravovaná pojistka</param>
        /// <returns>V případě úspěchu návrat na seznam pojistek, v případě neúspěchu pohled s vyplněným formulářem</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Type,InsuredPersonId,InsurerId,InsuredAmount,Instalment,InsuranceStartDate,InsuranceEndDate")] Insurance insurance)
        {
            if (id != insurance.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid && insurance.IsInstalmentSmaller())
            {
                try
                {
                    _context.Update(insurance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InsuranceExists(insurance.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            else ViewBag.Error = "Splátka nesmí být větší než celková suma.";
            ViewData["InsuredPersonId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber", insurance.InsuredPersonId);
            ViewData["InsurerId"] = new SelectList(from person in _context.Client select new { person.Id, person.BirthNumber }, "Id", "BirthNumber");
            return View(insurance);
        }
        /// <summary>
        /// Metoda Delete GET. Zobrazení formuláře s údaji o pojistce k vymazání.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <returns>V případě úspěchu pohled s modelem mazané pojistky.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var insurance = await _context.Insurance
                .Include(i => i.InsuredPerson)
                .Include(i => i.Insurer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (insurance == null)
            {
                return NotFound();
            }
            return View(insurance);
        }
        /// <summary>
        /// Metoda Delete POST. Odeslání formuláře s potvrzením vymazání pojistky.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <returns>V případě úspěchu a vymazání pojistky návrat na přehled pojistek. V případě neúspěchu pohled s modelem pojistky.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var insurance = await _context.Insurance.FindAsync(id);
            var events = await _context.InsuredEvent
                .FirstAsync(m => m.InsuranceId == id);
            if (insurance != null && events == null)
            {
                _context.Insurance.Remove(insurance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Error = "K této pojistce se váže pojistná událost, nejdříve je nutné ji odstranit.";
            return View(insurance);
        }
        /// <summary>
        /// Kontrola existence pojistky.
        /// </summary>
        /// <param name="id">Číselný identifikátor pojistky</param>
        /// <returns>True pokud je pojistka nalezena</returns>
        private bool InsuranceExists(int id)
        {
            return _context.Insurance.Any(e => e.Id == id);
        }
    }
}

InsuranceCompany/Views/InsuredEvents/Create.cshtml
@model InsuranceCompany.Models.InsuredEvent

@{
    ViewData["Title"] = "Tvorba pojistné události";
}

<section class="bg-dark py-5">
    <div class="container px-5 my-5 px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form class="d-flex flex-column gap-4" id="contactForm" asp-action="Create">
                    <div class="form-floating mb-3">
                        <input class="form-control" type="text" value="@ViewBag.Insurance.Type" disabled />
                        <label asp-for="Insurance.Type"></label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" type="text" value="@ViewBag.Client.FirstName" disabled />
                        <label asp-for="Insurance.InsuredPerson.FirstName"></label>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" type="text" value="@ViewBag.Client.LastName" disabled />
                        <label asp-for="Insurance.InsuredPerson.LastName"></label>
                    </div>
                </form>
                <form class="d-flex flex-column gap-4" id="contactForm" asp-action="Create">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Description" type="text" />
                        <label asp-for="Description"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="State" asp-items="@Html.GetEnumSelectList<InsuredEvent.EventState>()"></select>
                        <label asp-for="State"></label>
                    </div>
                    <div class="d-grid">
                        <button class="btn btn-primary btn-lg" type="submit">Odeslat</button>
                    </div>
                    <div class="d-grid">
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceId" type="text" value="@ViewBag.Insurance.Id" hidden />
                        <label asp-for="InsuranceId"></label>
                        <span asp-validation-for="InsuranceId" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="ClientId" type="text" value="@ViewBag.Client.Id" hidden />
                        <label asp-for="ClientId"></label>
                        <span asp-validation-for="ClientId" class="text-danger"></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        let form = document.querySelector('#the-form');
        form.addEventListener('submit', () => {
            let inputs = form.querySelectorAll('input');
            for (let input of inputs) {
                if (!input.value) {
                    input.disabled = true;
                }
            }
        })
    </script>
}

InsuranceCompany/Views/InsuredEvents/Delete.cshtml
@model InsuranceCompany.Models.InsuredEvent

@{
    ViewData["Title"] = "Vymazání události";
}

<section class="bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div class="text-center my-5">
                    <h1 class="display-5 fw-bolder text-white mb-2">Vymazání pojistky</h1>
                    <p class="lead text-white-50 mb-4">Opravdu si přejete ji smazat?</p>
                    <div class="text-white">
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Description)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Description)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.State)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.State)
                            </dd>
                        </dl>
                    </div>
                    <hr />
                    <form class="d-grid" asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Smaž" class="btn btn-danger btn-lg" />
                        <hr />
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

InsuranceCompany/Views/InsuredEvents/Edit.cshtml
@model InsuranceCompany.Models.InsuredEvent

@{
    ViewData["Title"] = "Upravit událost";
}

<section class="bg-dark py-5">
    <div class="container px-5 my-5 px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <form class="d-flex flex-column gap-4" id="contactForm" asp-action="Edit">
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="Description" type="text" />
                        <label asp-for="Description"></label>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-floating mb-3">
                        <select class="form-control" asp-for="State" asp-items="@Html.GetEnumSelectList<InsuredEvent.EventState>()"></select>
                        <label asp-for="State"></label>
                    </div>
                    <div class="d-grid">
                        <input type="submit" value="Odeslat" class="btn btn-primary btn-lg" />
                    </div>
                    <div class="d-grid">
                        <a href="#" class="btn btn-outline-light btn-lg px-4" onclick="window.history.go(-1); return false;">Zpět</a>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="InsuranceId" type="text" />
                        <label asp-for="InsuranceId"></label>
                        <span asp-validation-for="InsuranceId" class="text-danger" hidden></span>
                    </div>
                    <div class="form-floating mb-3">
                        <input class="form-control" asp-for="ClientId" type="text" hidden />
                        <label asp-for="ClientId"></label>
                        <span asp-validation-for="ClientId" class="text-danger"></span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InsuranceCompany/Views/InsuredEvents/Index.cshtml
@model IEnumerable<InsuranceCompany.Models.InsuredEvent>

@{
    ViewData["Title"] = "Správa Pojistných Událostí";
}

<section class="bg-dark py-5 border-bottom text-white">
    <div class="container px-5 my-5">
        <div class="text-center mb-5">
            <h2 class="fw-bolder">Správa pojistných událostí</h2>
        </div>
        <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
            <a class="btn btn-outline-light btn-lg px-4" asp-controller="Insurances" asp-action="Index">Správa pojištění</a>
            <a class="btn btn-outline-light btn-lg px-4" asp-controller="Clients" asp-action="Index">Správa osob</a>
        </div>
    </div>
    <div class="container">
        <table class="table table-responsive table-hover table-striped table-bordered">
            <thead class="table-dark">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Insurance.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Insurance.InsuredPerson.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.State)
                    </th>
                    <th class="text-center">
                        Akce
                    </th>
                </tr>
            </thead>
            <tbody class="table-light">
                @foreach (var item in Model) 
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Insurance.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Client.FirstName) @Html.DisplayFor(modelItem => item.Client.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.State)
                        </td>
                        <td class="text-center">
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>